name: Build and Push
on:
  push:
    branches: [main]
    # Only trigger if files in these folders change
    paths:
      - "bend/**"
      - "fend/**"
      - ".github/workflows/build.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Buildx is required for high-performance caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- BACKEND BUILD ---
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./bend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/farm-backend:2.0.8 #ver
          # Speeds up builds by caching layers in GitHub Actions
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- FRONTEND BUILD ---
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./fend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/farm-frontend:2.1.7
          cache-from: type=gha
          cache-to: type=gha,mode=max
